<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Description_TargetContent</name>
   <tag></tag>
   <elementGuidId>c5541ecf-230a-494f-b96d-edbac19ee9e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ptifrmtgtframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ptifrmtgtframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ptifrmtgtframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TargetContent</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Main Content</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>ptrc.onLoadTC()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://devstu.apu.edu/psc/DEVSTU/EMPLOYEE/SA/c/CC_BIO_DEMO_DATA_STDNT.SCC_BIO_DEMO.GBL?FolderPath=PORTAL_ROOT_OBJECT.HCCC_BUILD_COMMUNITY.HCCC_PERSONAL_INFO_STUDENT.HC_SCC_BIO_DEMO_GBL1&amp;IsFolder=false&amp;IgnoreParamTempl=FolderPath%2cIsFolder&amp;PortalActualURL=https%3a%2f%2fdevstu.apu.edu%2fpsc%2fDEVSTU%2fEMPLOYEE%2fSA%2fc%2fCC_BIO_DEMO_DATA_STDNT.SCC_BIO_DEMO.GBL&amp;PortalContentURL=https%3a%2f%2fdevstu.apu.edu%2fpsc%2fDEVSTU%2fEMPLOYEE%2fSA%2fc%2fCC_BIO_DEMO_DATA_STDNT.SCC_BIO_DEMO.GBL&amp;PortalContentProvider=SA&amp;PortalCRefLabel=Add%2fUpdate%20a%20Person&amp;PortalRegistryName=EMPLOYEE&amp;PortalServletURI=https%3a%2f%2fdevstu.apu.edu%2fpsp%2fDEVSTU%2f&amp;PortalURI=https%3a%2f%2fdevstu.apu.edu%2fpsc%2fDEVSTU%2f&amp;PortalHostNode=SA&amp;NoCrumbs=yes&amp;PortalKeyStruct=yes</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ptifrmtgtframe&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ptifrmtgtframe']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ptifrmtarget']/iframe</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
   </webElementXpaths>
</WebElementEntity>
